export default function Head() {
  return (
    <>
      <title>ShrutiCodes</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/Girl.svg" className="w-1 h-1" />
    </>
  );
}
